# Site settings
title: eQuanta
description: Diligentia laborat in omnis silvae et maria
baseurl: "" # the subpath of your site, e.g. /blog
url: https://leroy1977.github.io/eQ1/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# Diligentia laborat in omnis silvae, flumem et maria.

# enable automatic sitemap generation
# gems:
#       - jekyll-sitemap

# User settings
username: eQuanta
user_description: Organizada pela experiência de mais de 10 anos de sua equipe base, a eQuanta opera desde 2013 previlegiando rigor técnico, custo-efetividade e excelência, em relações de cooperação, transparência e sinergia. Concebida em 2011 por Euro Silva L. F. e Jorge de Oliveira E., atualmente é gerida por Euro S.L.F.. Conta com o suporte técnico e estratégico do biólogo e doutor em sócioecologia Rafael E. Ummus, experiente em diagnóstico, planejamento e implantação de projetos socioambientais, gestão e uso público de áreas naturais e recursos hídricos. A eQuanta também conta com uma equipe de consultores, mestres e doutores, de especialidades variadas, organizada com base nas características de cada projeto.
                
user_title: Diligentia laborat in omnis silvae et maria
email: e.quanta.env@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# facebook_username:  @eQuanta.env


# Google-analytics
google-analytics:
  id: "UA-97464337-1"

exclude: ['package.json', 'src' , 'node_modules']
