# Site settings
title: eQ
description: Diligentia laborat omnis silvae et maria
baseurl: "" # the subpath of your site, e.g. /blog
url: https://leroy1977.github.io/eQ1/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: eQuanta
user_description: Organizada a partir da experiência de mais de 15 anos de sua equipe, a eQuanta iniciou suas atividades em 2013, 
propondo abordagens orgânicas de cooperação e sinergia entre profissionais e clientes, aliando rigor técnico, 
custo-efetividade e excelência nas relações.
                Nosso principal objeto é o diagnóstico, gestão e recuperação da biodiversidade, em ambientes marinhos, dulcícolas e terrestres,
em interação com a diversidade cultural e pluralidade de atores inerente às questões socioambientais.
                Acreditamos que a sustentabilidade socioecológica é possível e pode ser construída a partir da produção e uso do conhecimento técnico, científico e tradicional, em processos interativos e participativos..</p>
                Nossa atuação técnica é pautada na utilização de conhecimento e ferramentas de vanguarda, atuando 
em conjunto com metodologias consolidadas e reconhecidas.
user_title: Diligentia laborat omnis silvae et maria
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
facebook_username: @eQuanta.env

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
