# Site settings
title: eQuanta
description: <i> Diligentia laborat in omnis silvae et maria </i>
baseurl: "" # the subpath of your site, e.g. /blog
url: https://leroy1977.github.io/eQ1/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# Diligentia laborat in omnis silvae, flumem et maria.

# enable automatic sitemap generation
# gems:
#       - jekyll-sitemap

# User settings
username: eQuanta
user_description: Organizada pela experiência de mais de 10 anos de sua equipe base, a eQuanta opera desde 2013 aliando rigor técnico e custo-efetividade, em relações de cooperação, transparência e sinergia. Somos uma equipe de consultores, mestres e doutores em diferentes especialidades, organizada segundo as características de cada projeto ambiental. Atendemos a organizações, governos e empresas interessadas em valorizar seus negócios através da sustentabilidade.
                
user_title: <p> <i> Diligentia laborat in omnis silvae et maria </i> <br> &bull; &bull; &bull; <br>Benvindos à nossa landing page! </p>
email: e.quanta.env@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# facebook_username:  @eQuanta.env


# Google-analytics
google-analytics:
  id: "UA-97464337-1"

exclude: ['package.json', 'src' , 'node_modules']
