# Site settings
title: eQuanta
description: Diligentia laborat in omnis silvae et maria
baseurl: "" # the subpath of your site, e.g. /blog
url: https://leroy1977.github.io/eQ1/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# Diligentia laborat in omnis silvae, flumem et maria.

# enable automatic sitemap generation
# gems:
#  - jekyll-sitemap

# User settings
username: eQuanta
user_description: Organizada a partir da experiência de mais de 15 anos de sua equipe base, a eQuanta opera desde 2013, previlegiando rigor técnico, custo-efetividade e excelência, em relações de cooperação, transparência e sinergia entre profissionais e clientes. É dirigida por Euro Silva Lopes Filho, biólogo e mestre em Ecologia de Ecossistemas, especializado em diagnósticos sócio-ambientais, planejamento e implantação de estudos sobre biodiversidade, com ênfase nos ecossistemas marinhos. Conta com o suporte técnico e estratégico do biólogo e mestre em Ciência Ambiental Rafael Eichemberger Ummus, especializado em diagnóstico, planejamento e implantação de projetos ambientais, facilitação de processos, biodiversidade, uso público de áreas naturais e recursos hídricos. A eQuanta também conta em sua equipe base com consultores de especialidades variadas.
                
user_title: Diligentia laborat in omnis silvae et maria
email: e.quanta.env@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# facebook_username:  @eQuanta.env


# Google-analytics
google-analytics:
  id: "UA-97464337-1"

exclude: ['package.json', 'src' , 'node_modules']
