# Site settings
title: eQ
description: Diligentia laborat in omnis silvae et maria
baseurl: "" # the subpath of your site, e.g. /blog
url: https://leroy1977.github.io/eQ1/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# Diligentia laborat in omnis silvae, flumem et maria.

# User settings
username: eQuanta
user_description: Organizada a partir da experiência de mais de 15 anos de sua equipe base, a eQuanta iniciou suas atividades em 2013, propondo abordagens orgânicas de cooperação e sinergia entre profissionais e clientes, aliando rigor técnico, custo-efetividade e excelência nas relações.
                
user_title: Diligentia laborat in omnis silvae et maria
email: euripes@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum
# facebook_username:  @eQuanta.env


# Google-analytics
google-analytics:
  id: "UA-97464337-1"

exclude: ['package.json', 'src' , 'node_modules']
